### ISSUE TITLE
please make logrotate defaults more sophisticated

### ISSUE THREAD

**Issue by gitterman** [logrotate/logrotate#128]
logrotate defaults to time frame "weekly" which is in most cases not the best solution.
Also many config file in logrotate.d use rotation by time frame which I regards as not optimized.
If logfiles are small there are many unnecessary log files which contain little information.
Time frame based  rotation is also susceptible to loose information from the past especially if log files grow slowly.
On the other hand, if logs are busy they can easily fill up the disk if rotated too slowly.
Thus I recommend to always use size based rotation.
I use the following defaults and comment most settings in the logrotate.d/* definitions to use those defaults
**size=5M
rotate 2
notifempty
create
missingok
compress
delaycompress**

```

**Comment by kdudka** [comment]
logrotate defaults to ```weekly``` rotation since 1997.  There was a big discussion about a minor change to the default semantics of ```weekly``` rotation recently (issue #93) and we agreed that it was better to stay consistent with the default behavior of logroate.  You are now proposing to rewrite the default configuration from scratch, which would not be well accepted by many users of logrotate.  If you do not like the default configuration of logroate, then just override it locally.
