### ISSUE TITLE
Failed to start logrotate service

### ISSUE THREAD

**Issue by code-share1** [logrotate/logrotate#242]
I use the latest logrotate version 3.15

```
# systemctl status logrotate
systemd[1]: Starting Rotate log files...
logrotate[6084]: error: wtmp:9 error verifying olddir path /root/logrotate_dir: No such file or directory
logrotate[6084]: error: found error in file wtmp, skipping
systemd[1]: logrotate.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: logrotate.service: Failed with result 'exit-code'.
```

Any hints?

**Comment by kdudka** [comment]
I think the cause is obvious from the diagnostic output.  You have something like `olddir /root/logrotate_dir` on line 9 in the `wtmp` configuration file of logrotate.  It is not clear where the configuration file is located on your system but it is usually in `/etc/logrotate.d`.  You might want to use the `createolddir ...` configuration directive.  Note that it is not very common configuration of logrotate to put rotated files under `/root`.  Was it you who wrote (or modified) the `wtmp` configuration file?

**Comment by code-share1** [comment]
Thanks, I confirmed that it is the config file problem and there is a service modify the /etc/logrotate.d/wtmp incorrectly.

Many thanks!

**Comment by kdudka** [comment]
Thanks for confirmation!
