### ISSUE TITLE
Readme does not include hourly option

### ISSUE THREAD

**Issue by AlexeyMinasyan** [logrotate/logrotate#249]
Readme.md states "Logrotate can be set to handle a log file daily, weekly, monthly or when the log file gets to a certain size."
But from man i see that there is an **hourly** option. 

Can this be added to avoid confusion?
Thanks.

**Comment by kdudka** [comment]
Thank you for reporting the issue!  Mentioning **hourly** in `README.md` is trivial.

The tricky part is that one needs to change the default cron hook (or systemd timer) to make **hourly** actually work as expected.  I did not find a suitable place in the documentation where this could be mentioned.  But I would probably keep the current `%description` wording in `logrotate.spec` because the spec file installs both the logrotate binary and the cron hook.
