### ISSUE TITLE
maxage calculation is off-by-1

### ISSUE THREAD

**Issue by urisimchoni** [logrotate/logrotate#39]
With maxage set, any log file older than N days needs to be purged. In effect, any file N+1 days old and older is purged (for example, with maxage set to 1, a file 25 hours old is not deleted - it is only deleted if it's 48 hours old or older).

**Comment by goeranu** [comment]
That depends on how you want to do the rounding.  How old is a file that is 25 hours old in days?  It is more than 1 day, but much less than 2 days.  Do we count that as 1 or 2 when it comes to “maxage”?

Obviously, there is no absolutely right or wrong.  Naïvely, I would probably have thought that `maxage 1` would mean everything 2 or more days old would be removed.  And I would probably have thought that would mean 2 _complete_ days, i.e. 48 hours or more.  Which is what logrotate currently implements, I believe.

After all, that would agree with how `find` interprets things.

As I said, there is hardly any clear right or wrong here, but IMHO it's better the way it is.

Adding a few tests would of course be great in either case.

**Comment by urisimchoni** [comment]
I'm a bit puzzled by this.

The manpage defines maxage as:
> Remove rotated logs older than count days.

When I have to buy tickets to the zoo, my 2.5-year-old daughter is not exempted because children older than 2 have to buy a ticket. So in my book the naive interpretation would be that `maxage 1` would mean that everything up to and including 1 complete days is kept, and everything else is deleted. There can be, of course, reasons for not following the naive interpretation (compatibility, complexity of implementation, etc.)

You're obviously correct about find:

> -atime n
> File  was  last  accessed n*24 hours ago.  When find figures out how many 24-hour periods ago the file was last accessed, any fractional part is ignored, so to match -atime +1, a file has to have been accessed at least  two days ago.

Wouldn't it be simpler if find man page said:
> -atime n
> File  was  last  accessed n*24 hours ago.

It seems that the manpage writer went to great lengths to account for this rounding, instead of just fixing find (could have his valid reasons).

**Comment by goeranu** [comment]
> When I have to buy tickets to the zoo, my 2.5-year-old daughter is not exempted because children older than 2 have to buy a ticket.

If I saw a sign _children up to the age of 2 go in free of charge_, and if I had a 2.5 years old daughter, I would most certainly expect her to go in without a ticket.  I call her 2 years old until the birthday when she becomes 3.  Maybe there are cultural differences here, and I don't know what your reference is.  But here in Sweden, if you ask for someone's age, you would get the number of _complete_ years they have lived.  Maybe with an added _turning X+1 on Saturday_ if the next upcoming birthday is close.

I have understood the _maxage_ parameter in the same way.

> -atime n
> File was last accessed n*24 hours ago.

Do you mean that a file that was 23:59:59 would not match this test, nor would a file 24:00:01?  That would be a pretty useless test then, it would almost never match.  You could still use the option for _less than_ or _greater than_ tests, but you would hardly ever be able to find files of a particular age.

For an age expressed in a number of days to make some sense, it has to refer to **some** 24 hour period.  You could probably argue which one. _X days old_ could probably be argued to mean
- strictly more than _(X-1)*24_  hours and less than or equal to _X*24_ hours,
- more than _X*24-12_ hours and less than _X*24+12_ hours, (with two sub-alternatives depending on which end you make open), or
- more than or equal to _X*24_ hours and strictly less than _(X+1)*24_ hours.

To me, the last one makes most sense.  As explained above, that is how I otherwise interpret the word _age_.

**Comment by urisimchoni** [comment]
I think we've uncovered a cultural difference. I interpret age to be a continuous quantity, a time interval. It can have any units - it doesn't change the age. So 25 hours is more than 24 hours, hence more than a day.

Since the existing behavior of logrotate matches your expectations I'm happy with closing this issue. I just needed this extra clarification, because the behavior doesn't meet my expectations.

Perhaps a clarification in the manpage, such as the one in `find` is in order.

Thanks,
Uri.

**Comment by goeranu** [comment]
> I think we've uncovered a cultural difference.

Interesting!  If you allow a question somewhat off topic: how would _you_ answer the question “what is your age?”  Of course, you don't have to reveal your real age if it would be sensitive!  :smile:  I'm just curious of the format, assuming this is not your birthday today.

**Comment by urisimchoni** [comment]
I've been saying I'm 44 ever since I turned 44 last August, but maybe now I'd answer "almost 45". I don't view the "how old are you" question as expecting me to provide a precise answer. To the question "are you over 44 years old?" I'd answer "Yes", and this may have consequences - as in the zoo example. Not sure the zoo example is a real one, because usually the wording is more precise - "children who have not turned 2 years are exempt".

Well, that's how things are in Israel anyway :)

PS, the definition of _age_ is not necessarily relevant to the logrotate manpage, it's the definition of _older than_, and here lies the cultural difference.
