### ISSUE TITLE
Several log entry enhancement

### ISSUE THREAD

**Issue by koryaga** [logrotate/logrotate#4]
Hi guys,

Currently logrotate doesn't support several rotation policies for one file (getting "duplicate log entry" error).
How about add this feature  ?

Use case: I need to rotate and preserve  same log file in different places and with different storing time. 
For example 5 last archive in /var/log and for one year in another long-term storage.
We have this requirement in our solution and I see that would be worth to do it by logrotate.
I think using additional "copy cron job" would be architecturally wrong beacuse of:
1. There might be a collusion while coping archive file to an additional storage. 
  Typical scenario when two different processes access shared file/files: file naming collusion (copying file which are being renamed), copy collision (cron is going to copy file which was just deleted) and so on
2. There will be dublicate of functionality in the cron script with logrotate (archiving, naming, rotating)  

Please let me know your oppinion,  if this enhancement is desired, follows lograte architecture.

Thank you.

**Comment by hanzz** [comment]
Hm, I'm afraid we won't be able to support this, sorry. Whole logrotate is designed with a premise that we rotate single log file just once. The architecture of logrotate would have to be changed a lot to support this feature and since we try to keep logrotate simple, I think it's not the right tool to use for this task.
