### ISSUE TITLE
if prerotate return error, the log is not dumped and the log package will be renamed

### ISSUE THREAD

**Issue by banjiuqingshan** [logrotate/logrotate#498]
![21DEC767-4A30-4484-92FA-651D17CFD0D0](https://user-images.githubusercontent.com/63209634/225863049-0c3bb852-438e-4495-b82e-be35a26dd151.png)
And we will lose the previous log

**Comment by cgzones** [comment]
This is indeed the current behavior.
The loss of the previous log file in your examples is caused by overriding the log file via dd(1), otherwise it would have been preserved.
I am not sure what the historic reason is to rotate the old logs first, then run the prerotate script and then rotate the current log file; and I am also not sure if we should reorder it now.
Probably we could improve the documentation about this behavior:

https://github.com/logrotate/logrotate/blob/be6a263c87915d0467f5148d1488dd07f82be23a/logrotate.8.in#L667-L668

**Comment by banjiuqingshan** [comment]
The original log will not be changed. I mean that logs that have been rotated will be renamed and overwritten, similar to test.log.3.gz, which will be renamed to test.log.4.gz, and then lost. In fact, all historical logs will be lost after several more executions. Can we reorder them or resume operations on the logs after the execution fails

**Comment by banjiuqingshan** [comment]
The issue has been resolved by https://github.com/logrotate/logrotate/commit/fd1892e425f1facbbf1cee260e3bc5673a819182.
